### ISSUE TITLE
No module named 'requests' when deploying eg to Heroku or Pythoneverywhere

### ISSUE THREAD

**Issue by klevamane** [edwardpopoola/pypaystack#9]
ERROR: Command errored out with exit status 1:
     command: /home/bitlebron/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-esugn3oq/pypaystack/setup.py'"'"'; __f
ile__='"'"'/tmp/pip-install-esugn3oq/pypaystack/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\
n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-esugn3oq/pypaystack/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-esugn3oq/pypaystack/setup.py", line 2, in <module>
        from pypaystack import version
      File "/tmp/pip-install-esugn3oq/pypaystack/pypaystack/__init__.py", line 3, in <module>
        from .customers import Customer
      File "/tmp/pip-install-esugn3oq/pypaystack/pypaystack/customers.py", line 1, in <module>
        from .baseapi import BaseAPI
      File "/tmp/pip-install-esugn3oq/pypaystack/pypaystack/baseapi.py", line 2, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'

**Comment by kunlegiwa** [comment]
Having similar issues deploying to GCP. is anyone able to look at this?

**Comment by mahmoudtokura** [comment]
@klevamane Hi, were you able to find a solution to this. Please advise if you did. Thanks

**Comment by klevamane** [comment]
Hi, @mahmoudtokura I wasn't able to find a solution to this per se, instead, I implemented Paystack manually using the APIs as opposed to using this package.
That was how I solved the issue.

**Comment by mahmoudtokura** [comment]
Hi, @klevamane I ended up manually installing it directly on the server but I think your approach is better for long-term support.
I'll do that in my next update.
Thanks

**Comment by sorXCode** [comment]
Try including `requests==2.26.0` in your project's `requirements.txt` file to fix this issue.

**Comment by Josh596** [comment]
@sorXCode It doesn't solve the issue

**Comment by mafking** [comment]
@mahmoudtokura [mahmoudtokura](https://github.com/mahmoudtokura)
please how did you install it directly to the server and were you using pythonanywhere or heroku

**Comment by klevamane** [comment]
@mafking  if it's heroku, you can access the console and install it from there. But the thing is, you may need to always do this when you push changes

**Comment by gray-adeyi** [comment]
Hi! I've republished this package as pypaystack2
```bash
pip install pypaystack2
```
No major changes were made it still works like 
pypaystack but you'll have to import from pypaystack2
more info at [PyPaystack2](https://github.com/gray-adeyi/pypaystack2)

**Comment by gray-adeyi** [comment]
Just published a new version. I made some changes that aren't backwards compatible with it. But I've tried hard to create a documentation for it you can check it out here. https://pypi.org/project/pypaystack2/

**Comment by gray-adeyi** [comment]
Hi! I just got a message from someone trying to use pypaystack2 about a bug. "error importing Optional from optparse". that's my fault. if you're experiencing the same issue i've fixed it in the version 1.0.1. https://pypi.org/project/pypaystack2/

**Comment by gray-adeyi** [comment]
Just added a simple tutorial to the documentation. you can find it out here https://gray-adeyi.github.io/pypaystack2/paystack-client-turorial.html

**Comment by gray-adeyi** [comment]
Merry Christmas developers! I'm glad to announce the release of version 1.0.2 of pypaystack2. Fixed bugs and included the the new Terminal API from paystack and a new way of using the API wrappers more info in the link
https://gray-adeyi.github.io/pypaystack2/how-to-guides/
